# Generated by Django 3.1 on 2021-01-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210121_0200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                choices=[
                    ("KR", "국어연구팀"),
                    ("MT", "수학연구팀"),
                    ("EG", "영어연구팀"),
                    ("SCI_PH", "물리학연구팀"),
                    ("SCI_CH", "화학연구팀"),
                    ("SCI_BS", "생명과학연구팀"),
                    ("SCI_GS", "지구과학연구팀"),
                    ("CM_KH", "한국사연구팀"),
                    ("CM_LAE", "생활과윤리연구팀"),
                    ("CM_AEI", "윤리와사상연구팀"),
                    ("CM_KRG", "한국지리연구팀"),
                    ("CM_WDG", "세계지리연구팀"),
                    ("CM_EAH", "동아시아사연구팀"),
                    ("CM_WDH", "세계사연구팀"),
                    ("CM_ECN", "경제연구팀"),
                    ("CM_PAL", "정치와법연구팀"),
                    ("CM_SCT", "사회문화연구팀"),
                    ("MS_EPD", "교육/인사팀"),
                    ("MS_FI", "회계팀"),
                    ("MS_LAW", "법무팀"),
                    ("MS_GA", "총무팀"),
                    ("TDD", "기술개발 본부"),
                    ("DDB", "디자인팀"),
                    ("VDO", "영상팀"),
                ],
                max_length=30,
                unique=True,
                verbose_name="팀명",
            ),
        ),
    ]
