# Generated by Django 3.1 on 2021-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210121_0206"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                choices=[
                    ("MS", "경영지원부"),
                    ("SCI", "과학탐구개발부"),
                    ("CM", "사회탐구개발부"),
                    ("KR", "국어개발부"),
                    ("MT", "수학개발부"),
                    ("EG", "영어개발부"),
                    ("DDB", "디자인부"),
                    ("TDD", "기술개발부"),
                    ("VDO", "영상부"),
                ],
                max_length=30,
                unique=True,
                verbose_name="부서명",
            ),
        ),
    ]
