# Generated by Django 3.1 on 2021-01-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20210121_0224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="approved",
        ),
    ]
