# Generated by Django 3.1 on 2020-09-11 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='설계 책임자'),
        ),
        migrations.AddField(
            model_name='project',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='편집 책임자'),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewer_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='1차 피드백 책임자'),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewer_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='2차 피드백 책임자'),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewer_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='3차 피드백 책임자'),
        ),
        migrations.AddField(
            model_name='project',
            name='selector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='선정 책임자'),
        ),
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.subject', verbose_name='과목'),
        ),
        migrations.AddField(
            model_name='history',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='projects.question'),
        ),
        migrations.AddField(
            model_name='history',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.history'),
        ),
    ]
