# Generated by Django 3.1 on 2020-08-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_auto_20200823_2110"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
