# Generated by Django 3.1 on 2020-08-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_question_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="history", name="image",),
        migrations.CreateModel(
            name="QuestionImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.ImageField(upload_to="")),
                ("caption", models.CharField(max_length=500, null=True)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.history",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
