# Generated by Django 3.1 on 2020-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_auto_20200824_1743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionimage",
            name="file",
            field=models.ImageField(upload_to="question_images"),
        ),
    ]
