# Generated by Django 3.1 on 2020-08-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_auto_20200824_1806"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="projects.project",
            ),
        ),
    ]
