# Generated by Django 3.1 on 2020-08-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_auto_20200824_1852"),
    ]

    operations = [
        migrations.RemoveField(model_name="questionimage", name="caption",),
    ]
