# Generated by Django 3.1 on 2020-08-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_question_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="group",
            field=models.CharField(
                choices=[
                    ("UNDEFINED", "Undefined"),
                    ("TEMP", "Temp"),
                    ("RAQ", "Raq"),
                    ("QTB", "Qtb"),
                    ("PJD", "Pjd"),
                ],
                default="UNDEFINED",
                max_length=10,
            ),
        ),
    ]
