# Generated by Django 3.1 on 2020-08-31 12:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_auto_20200829_0332"),
    ]

    operations = [
        migrations.RemoveField(model_name="history", name="complete",),
        migrations.RemoveField(model_name="history", name="difficulty",),
        migrations.RemoveField(model_name="history", name="integrity",),
        migrations.RemoveField(model_name="history", name="novelty",),
        migrations.RemoveField(model_name="history", name="order",),
        migrations.RemoveField(model_name="history", name="size",),
        migrations.AddField(
            model_name="history",
            name="answer",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="subject",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="illustration_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "difficulty",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="난이도",
                    ),
                ),
                (
                    "novelty",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="참신성",
                    ),
                ),
                (
                    "sympathy",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="호감도",
                    ),
                ),
                (
                    "integrity",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="구성력",
                    ),
                ),
                (
                    "application",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="단원응용력",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        choices=[(1, "소"), (2, "중"), (3, "대")], default=2
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.history",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
