# Generated by Django 3.1 on 2020-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_auto_20200831_2154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100, verbose_name="모의고사 명"),
        ),
    ]
