# Generated by Django 3.1 on 2020-09-01 02:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0014_auto_20200831_2156"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="designer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="설계 책임자",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="editor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="편집 책임자",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="editor_due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 1, 2, 16, 37, 193964),
                verbose_name="편집 마감기한",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="illustrator_due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 1, 2, 16, 37, 193964),
                verbose_name="일러 마감기한",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reviewer_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="1차 피드백 책임자",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reviewer_1_due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 1, 2, 16, 37, 193964),
                verbose_name="1차 피드백 마감기한",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reviewer_2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="2차 피드백 책임자",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reviewer_2_due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 1, 2, 16, 37, 193964),
                verbose_name="2차 피드백 마감기한",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reviewer_3",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="3차 피드백 책임자",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reviewer_3_due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 1, 2, 16, 37, 193964),
                verbose_name="3차 피드백 마감기한",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="selector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="선정 책임자",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="selector_due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 1, 2, 16, 37, 193964),
                verbose_name="대상 선정 마감기한",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 1, 2, 16, 37, 193964),
                verbose_name="전체 마감기한",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="size",
            field=models.IntegerField(
                choices=[(1, "소"), (2, "중"), (3, "대")], default=2, verbose_name="크기"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.subject",
                verbose_name="과목",
            ),
        ),
    ]
