# Generated by Django 3.1 on 2020-09-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_auto_20200901_0245"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="illustration_complete",),
    ]
