# Generated by Django 3.1 on 2020-09-03 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_remove_question_illustration_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="designer_due_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="설계 마감기한"
            ),
        ),
    ]
