# Generated by Django 3.1 on 2020-09-08 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_project_designer_due_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="designer_due_date",
            new_name="design_due_date",
        ),
        migrations.RenameField(
            model_name="project", old_name="editor_due_date", new_name="edit_due_date",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="reviewer_1_due_date",
            new_name="review_1_due_date",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="reviewer_2_due_date",
            new_name="review_2_due_date",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="reviewer_3_due_date",
            new_name="review_3_due_date",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="selector_due_date",
            new_name="select_due_date",
        ),
        migrations.RemoveField(model_name="project", name="illustrator_due_date",),
        migrations.AddField(
            model_name="project",
            name="design_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="edit_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="illustrate_1_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="illustrate_1_due_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="일러 1차 마감기한"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="illustrate_2_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="illustrate_2_due_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="일러 2차 마감기한"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="illustrate_3_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="illustrate_3_due_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="일러 3차 마감기한"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="review_1_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="review_2_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="review_3_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="select_complete",
            field=models.BooleanField(default=False),
        ),
    ]
