# Generated by Django 3.1 on 2020-09-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_auto_20200908_0444"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="design_complete",
            new_name="design_completed",
        ),
        migrations.RenameField(
            model_name="project", old_name="edit_complete", new_name="edit_completed",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="illustration_1_complete",
            new_name="illustration_1_completed",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="illustration_2_complete",
            new_name="illustration_2_completed",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="illustration_3_complete",
            new_name="illustration_3_completed",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="review_2_complete",
            new_name="review_1_completed",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="review_1_complete",
            new_name="review_2_completed",
        ),
        migrations.RemoveField(model_name="project", name="review_3_complete",),
        migrations.RemoveField(model_name="project", name="select_complete",),
        migrations.AddField(
            model_name="project",
            name="review_3_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="select_completed",
            field=models.BooleanField(default=False),
        ),
    ]
