# Generated by Django 3.1 on 2020-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_auto_20200909_0654"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="design_completed",
            field=models.BooleanField(default=True),
        ),
    ]
