# Generated by Django 3.1 on 2020-09-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_auto_20200909_0718"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="design_completed",),
    ]
