# Generated by Django 3.1 on 2020-12-27 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="end_datetime",),
        migrations.RemoveField(model_name="reservation", name="start_datetime",),
        migrations.AddField(
            model_name="reservation",
            name="end_time",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="회의실 번호",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_time",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
                verbose_name="회의실 번호",
            ),
            preserve_default=False,
        ),
    ]
