# Generated by Django 3.1 on 2020-12-27 01:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0002_auto_20201227_0002"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end_time",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="회의 끝 일시",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
                verbose_name="회의 시작 일시 ",
            ),
        ),
    ]
