# Generated by Django 3.1 on 2020-12-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0003_auto_20201227_0115"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation", unique_together={("date", "start_time")},
        ),
    ]
