# Generated by Django 3.1 on 2021-01-17 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0005_remove_reservation_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(47),
                ],
                verbose_name="회의 시작 일시 ",
            ),
        ),
    ]
