# Generated by Django 3.1 on 2021-01-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0006_auto_20210117_0519"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("room", "date", "start_time")},
        ),
    ]
