# Generated by Django 3.1 on 2021-02-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0002_auto_20210120_2200"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ["-created_at"]},
        ),
    ]
