# Generated by Django 3.1 on 2021-01-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterlog',
            options={'ordering': ['date', 'time']},
        ),
    ]
