# Generated by Django 3.1 on 2021-02-02 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workhours", "0002_auto_20210107_1945"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkHourCorrectionRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.IntegerField(choices=[(1, "출근"), (2, "퇴근"), (3, "출입")]),
                ),
                ("date", models.DateField(verbose_name="통행 날짜")),
                ("time", models.TimeField(verbose_name="통행 시각")),
                ("reason", models.CharField(max_length=1000, verbose_name="사유")),
                (
                    "workhour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="workhours.workhour",
                        verbose_name="원본 근무 시간",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
