# Generated by Django 3.1 on 2021-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workhours", "0003_workhourcorrectionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhourcorrectionrequest",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
