# Generated by Django 3.1 on 2021-02-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workhours", "0004_workhourcorrectionrequest_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhourcorrectionrequest",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
