# Generated by Django 3.1 on 2021-02-04 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workhours", "0005_workhourcorrectionrequest_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhourcorrectionrequest",
            name="approver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workhour_correction_decisions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="결재자",
            ),
        ),
    ]
