# Generated by Django 3.1 on 2021-02-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workhours", "0006_workhourcorrectionrequest_approver"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhourcorrectionrequest",
            name="diff",
            field=models.CharField(max_length=1500, null=True, verbose_name="수정 상세사항"),
        ),
    ]
